variables:
    GIT_SUBMODULE_STRATEGY: recursive
    PROJECT_NAME: block-control

before_script:
    - git clone --branch=master --depth=1 --quiet git@git.kittmedia.com:wordpress/deploy-script.git
    - chmod +x deploy-script/*.sh


stages:
    - test
    - production

upload_zip_updateserver:
    stage: production

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_PRODUCTION -d $DEPLOY_PATH -h $DEPLOY_SERVER -z $PROJECT_NAME --gutenberg-block

    only:
        - tags

    variables:
        DEPLOY_PATH: /var/www/wp-update-server/packages
        DEPLOY_SERVER: dagobah.kittmedia.com

        # GitLab project variables:
        # - SSH_USER_PRODUCTION

upload_zip_updateserver_dev:
    stage: test

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_PRODUCTION -d $DEPLOY_PATH -h $DEPLOY_SERVER -z ${PROJECT_NAME}-dev --gutenberg-block

    variables:
        DEPLOY_PATH: /var/www/wp-update-server/packages
        DEPLOY_SERVER: dagobah.kittmedia.com

        # GitLab project variables:
        # - SSH_USER_PRODUCTION

upload_zip_product:
    stage: production

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_PRODUCTION -d $DEPLOY_PATH -h $DEPLOY_SERVER -z $PROJECT_NAME --gutenberg-block

    only:
        - tags

    variables:
        DEPLOY_PATH: /var/www/epiphyt/wp-content/uploads/products/${PROJECT_NAME}-xjprz348qruqo348tz4at84
        DEPLOY_SERVER: dagobah.kittmedia.com

        # GitLab project variables:
        # - SSH_USER_PRODUCTION

wd50_northstar:
    stage: test

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_RH_USER_TEST -d $DEPLOY_PATH -h $DEPLOY_SERVER --gutenberg-block

    only:
        - master

    variables:
        DEPLOY_PATH: /var/www/wd50/wp-content/plugins/${PROJECT_NAME}
        DEPLOY_SERVER: northstar.li

        # GitLab project variables:
        # - SSH_RH_USER_TEST
