name: Plugin asset/readme update
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
jobs:
  main:
    name: Asset update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Run npm build
    - uses: bahmutov/npm-install@v1
    - name: Run
      run: npm run build
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        README_NAME: README.md
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
